[auth]
algorithm = "HS256"
access_token_expires = 30

[club_details]
name = "IEEE Computer Society"
roles = ["UPPER_MANAGEMENT", "DEPARTMENT_LEADS", "JUNIOR_DEPARTMENT_LEADS", "MEMBER"]
departments = ["TECHNICAL", "MANAGEMENT", "SOCIAL_MEDIA", "DESIGN"]